# Generated by Django 4.1.5 on 2023-01-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
